/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.e2p1_joselobo;

import java.awt.Color;

/**
 *
 * @author rinal
 */
public class Interfaz extends javax.swing.JFrame {

    Procesos P = new Procesos();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearMaquina = new javax.swing.JFrame();
        Titulocrear = new javax.swing.JLabel();
        Tituloestado = new javax.swing.JLabel();
        TituloTransicion = new javax.swing.JLabel();
        Estados = new javax.swing.JTextField();
        Transiciones = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        ComputarCadena = new javax.swing.JFrame();
        Computar = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        TituloCadena = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CadenaComputar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Respuesta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Evaluar = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        CrearMaquina.setName("Crear Maquina"); // NOI18N

        Titulocrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Titulocrear.setText("Crear Maquina");

        Tituloestado.setText("Estados");

        TituloTransicion.setText("Transiciones");

        Estados.setText("q1;.q2;q3");
        Estados.setToolTipText("");
        Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadosActionPerformed(evt);
            }
        });

        Transiciones.setText("q1,0,q1;q1,1,q2;q2,0,q3;q2,1,q2;q3,0,q2;q3,1,q2");
        Transiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransicionesActionPerformed(evt);
            }
        });

        Create.setText("Crear");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearMaquinaLayout = new javax.swing.GroupLayout(CrearMaquina.getContentPane());
        CrearMaquina.getContentPane().setLayout(CrearMaquinaLayout);
        CrearMaquinaLayout.setHorizontalGroup(
            CrearMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearMaquinaLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(Titulocrear)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(CrearMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CrearMaquinaLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addGroup(CrearMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TituloTransicion)
                        .addComponent(Tituloestado)
                        .addComponent(Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CrearMaquinaLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(Create)))
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
        CrearMaquinaLayout.setVerticalGroup(
            CrearMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearMaquinaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Titulocrear)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(CrearMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CrearMaquinaLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(Tituloestado)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(TituloTransicion)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(Create)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        Computar.setText("Computar");
        Computar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputarActionPerformed(evt);
            }
        });

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        TituloCadena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloCadena.setText("Computar Cadena");

        jLabel1.setText("Cadena a Computar");

        CadenaComputar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadenaComputarActionPerformed(evt);
            }
        });

        Respuesta.setColumns(20);
        Respuesta.setRows(5);
        jScrollPane1.setViewportView(Respuesta);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jLabel2.setText("Posdata: No Supe arreglar el Null");

        javax.swing.GroupLayout ComputarCadenaLayout = new javax.swing.GroupLayout(ComputarCadena.getContentPane());
        ComputarCadena.getContentPane().setLayout(ComputarCadenaLayout);
        ComputarCadenaLayout.setHorizontalGroup(
            ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputarCadenaLayout.createSequentialGroup()
                .addGroup(ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputarCadenaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(CadenaComputar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                    .addGroup(ComputarCadenaLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Computar)
                            .addGroup(ComputarCadenaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Menu)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2))))
                    .addGroup(ComputarCadenaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(TituloCadena)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        ComputarCadenaLayout.setVerticalGroup(
            ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputarCadenaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(TituloCadena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadenaComputar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Computar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComputarCadenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Lab P1 - Examen II"); // NOI18N

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Lab P1 - Examen II");

        Evaluar.setText("Evaluar Cadena");
        Evaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluarActionPerformed(evt);
            }
        });

        Crear.setText("Crear Maquina");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearMouseExited(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Evaluar)
                    .addComponent(Titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(salir)))
                .addGap(106, 106, 106))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(Crear)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Titulo)
                .addGap(106, 106, 106)
                .addComponent(Evaluar)
                .addGap(44, 44, 44)
                .addComponent(salir)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(Crear)
                    .addContainerGap(175, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseExited

    }//GEN-LAST:event_CrearMouseExited

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        CrearMaquina.setVisible(true);
        CrearMaquina.pack();
    }//GEN-LAST:event_CrearActionPerformed

    private void EvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluarActionPerformed
        // TODO add your handling code here:
        ComputarCadena.setVisible(true);
        ComputarCadena.pack();
    }//GEN-LAST:event_EvaluarActionPerformed

    private void EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadosActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        CrearMaquina.setVisible(false);
        
    }//GEN-LAST:event_CreateActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        ComputarCadena.setVisible(false);
    }//GEN-LAST:event_MenuActionPerformed

    private void TransicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransicionesActionPerformed

    private void ComputarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputarActionPerformed
        String[] answer = P.MaquinaEstadosstado(Estados.getText(),Transiciones.getText(),CadenaComputar.getText());
        Respuesta.setText(answer[0]+answer[1]+answer[2]);
    }//GEN-LAST:event_ComputarActionPerformed

    private void CadenaComputarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadenaComputarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadenaComputarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadenaComputar;
    private javax.swing.JButton Computar;
    private javax.swing.JFrame ComputarCadena;
    private javax.swing.JButton Crear;
    private javax.swing.JFrame CrearMaquina;
    private javax.swing.JButton Create;
    private javax.swing.JTextField Estados;
    private javax.swing.JButton Evaluar;
    private javax.swing.JButton Menu;
    private javax.swing.JTextArea Respuesta;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloCadena;
    private javax.swing.JLabel TituloTransicion;
    private javax.swing.JLabel Titulocrear;
    private javax.swing.JLabel Tituloestado;
    private javax.swing.JTextField Transiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
